# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokers', to='logreg_app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='logreg_app.User')),
            ],
        ),
    ]
